name: Docker Image CI and Save Artifact

on:
  push:
    branches: [ "master" ]
  # Maybe remove pull_request trigger if you only want artifacts on push
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build-and-save:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      # Use a predictable tag, like the commit SHA, instead of date
      run: docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}

    - name: Save Docker image to tar file
      # Output is my-image-name.tar (using the SHA in the filename helps too)
      run: docker save my-image-name:${{ github.sha }} -o my-image-name-${{ github.sha }}.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image # Name of the artifact shown on GitHub
        path: my-image-name-${{ github.sha }}.tar # Path to the file to upload
